- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  vars:
    keypair: my_keypair
    instance_type: m1.small
    firewall_group_id: sg-cdcf30b8
    ami_id: ami-049e32cfbee0696cd 
    aws_region: us-east-1
    
  tasks:
  - name: Create an EC2 instance
    ec2:
      key_name: "{{keypair}}"
      region: "{{aws_region}}"
      group_id: "{{firewall_group_id}}"
      instance_type: "{{instance_type}}"
      image: "{{ami_id}}"
      wait: yes
      volumes:
        - device_name: /dev/sda1
          volume_type: gp2
          volume_size: 100
          delete_on_termination: true
      exact_count: 6
      count_tag:
         Name: ansible-demo
      instance_tags:
         Name: ansible-demo
    register: ec2
