# Basic provisioning example
- name: Create AWS resources
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    name_ec2: "{{ name_mv }}"
   
  tasks:
  - name: create an EC2 instance
    ec2:
      instance_tags:
        Name: "{{ name_ec2 }}"                  #ingrese el nombre de la instancia
      key_name: my_keypair           #Ingrese la llave con nombre my_keypair
      region: us-east-2                #Ingrese la región de AWS.
      group_id: sg-0b73a81245dba7c19   #Ingrese el group ID
      instance_type: t2.micro          # Ingrese el type.
      image: ami-00cbb7bf4617ee51d    # Ingrese el ami ID.
      wait: yes
      vpc_subnet_id: subnet-824712ce
    register: basic_ec2
