- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  vars:
    keypair: my_keypair
    instance_type: m1.small
    firewall_group_id: sg-cdcf30b8
    ami_id: ami-07a0844029df33d7d #verificar que este ID exista en la zona de disponibilidad
    aws_region: us-east-2
    vpc_ids: "vpc-da74f8b1"
    cidr_ips: 172.31.0.0
    aws_access_key: AKIA2BW734Q34VCTYNR7
    aws_secret_key: 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
  tasks:
    - name: Provision instance
      ec2:
#        aws_access_key: "{{ aws_access_key }}"
#        aws_secret_key: "{{ aws_secret_key }}"
        key_name: "{{keypair}}"
        instance_type: "{{instance_type}}"
        image: "{{ami_id}}"
        wait: yes
        count: 1
        region: "{{aws_region}}"
