---
- name: Create a sandbox instance
  hosts: localhost
  connection: local
  become: False
  gather_facts: False
  vars:
    key_name: my_keypair
    instance_type: t2.micro
    firewall_group_id: sg-03d829ffb469c64d9
    ami_id: ami-07a0844029df33d7d    #verificar que este ID exista en la zona de disponibilidad
    aws_region: us-east-2
    vpc_ids: vpc-da74f8b1
    cidr_ips: 172.31.0.0
    aws_access_key: "{{ aws_access_keys }}"
    aws_secret_key: "{{ aws_secret_keys }}"
  tasks:
    - name: Provision instance
      ec2:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image: "{{ ami_id }}"
        region: "{{ aws_region }}"
        wait: yes
        group: Ansible
        count: 1
        vpc_subnet_id: subnet-3974a652
        assign_public_ip: yes
